import Head from 'next/head';


export default function Home() {
    return (
        <div className="h-screen flex items-center justify-center bg-gradient-to-br from-orange-500 via-red-500 to-pink-500">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-6 w-48 rounded-lg bg-white shadow-lg">
                <h1 className="font-bold text-2xl">GunnHacks.</h1>
                <p>It is occurring!</p>
            </main>
        </div>
    )
}
